### ISSUE TITLE
ERROR | [iOS] [xcodebuild]  KZRobot/KZRobot/Robot/XCRoboticTestCase.h:9:9: fatal error: 'XCTest/XCTest.h' file not found

### ISSUE THREAD

**Issue by akrambek** [k3po/k3po.ios#1]
CocoCocoaPods is failing to validate podspec file in  Xcode 6. In order to fix this for any CocoaPod dependencies we need to add the following to FRAMEWORK_SEARCH_PATHS in any Pod target that requires XCTest (e.g. Kiwi, Specta, FBSnapshotTestCase, etc).

$(PLATFORM_DIR)/Developer/Library/Frameworks

This will allow you to reference XCTest in any dependencies you may have. This may be fixed in a future update of CocoaPods, or the Pod you are referencing, so you may want to remove it later.

It is not detrimental to earlier versions of Xcode so should be safe to use.

**Comment by sanjay-saxena** [comment]
Closing out this issue as the implementation has changed.
